### ISSUE TITLE
apigeetool deployproxy is failing on Linux OS

### ISSUE THREAD

**Issue by RaoParupalli** [apigee/apigeetool-node#236]
The recent version of apigeetool is failing on Linux Vms with the following error. And chaning the value from "deployProxy" to "deployproxy" in apigeetool/lib/commands/commands.js file seems to work fine.

Error: Cannot find module './deployProxy'
Require stack:
- /home/AzDevOps/.npm/_npx/1a473e145b816643/node_modules/apigeetool/lib/commands/commands.js
- /home/AzDevOps/.npm/_npx/1a473e145b816643/node_modules/apigeetool/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.load (/home/AzDevOps/.npm/_npx/1a473e145b816643/node_modules/apigeetool/lib/commands/commands.js:75:17)
    at Object.<anonymous> (/home/AzDevOps/.npm/_npx/1a473e145b816643/node_modules/apigeetool/lib/cli.js:22:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',

**Comment by RomanKreisel** [comment]
I'm experiencing the same issue since this morning.
First thought was, because we went from Node16 to Node20 - but it seems to have just changed overnight - maybe because some package dependencies in npmjs?

At least, right now, we're unable to perform any more deployments using this tool :(

**Comment by DinoChiesa** [comment]
This should be fixed. It's been released to npm.
