### ISSUE TITLE
apigeetool fails to upload proxy files (in some circumstances)

### ISSUE THREAD

**Issue by oseymen-apigee** [apigee/apigeetool-node#28]
Hi all

We are using apigeetool to deploy our bundles via executing them from grunt shell.

We have 3 proxy files under /proxies folder:
- admin.xml
- default.xml
- monitoring.xml

When using the latest version of apigeetool (0.6.1), we realised that none of the proxy files are imported into Apigee. Here is the full log:

```
Running "shell:deploy" (shell) task
deployproxy: {"debug":true,"verbose":true,"username":"email-address-for-deployment","password":{},"organization":"org-here","environments":"intg","api":"b2b-otaxml","directory":".","baseuri":"https://api.enterprise.apigee.com","asyncLimit":4}
Resolve NPM modules = false
Going to create revision 205 of API b2b-otaxml
Calling https://api.enterprise.apigee.com/v1/o/org-here/apis?action=import&validate=false&name=b2b-otaxml
Creating revision 205 of API b2b-otaxml
Uploading jsc resource AuthorizeIpAddress.js
Uploading jsc resource ConvertConfigurationToJson.js
Uploading jsc resource ExtractConfigurationVariables.js
Uploading jsc resource ExtractInvalidateCacheRequestVariables.js
Uploading jsc resource ModifyAvailabilityCacheResponse.js
Uploading jsc resource logglyDirect.js
Uploading node resource Gruntfile.js
Uploading node resource api/controllers/fitController.js
Uploading node resource api/controllers/statusController.js
Uploading node resource api/converters/availabilityConverter.js
Uploading node resource api/converters/cancellationConverter.js
Uploading node resource api/converters/fetchReservationConverter.js
Uploading node resource api/converters/reservationConverter.js
Uploading node resource api/handlers/invalidRequestHandler.js
Uploading node resource api/handlers/otaAvailabilityRequestHandler.js
Uploading node resource api/handlers/otaCancellationRequestHandler.js
Uploading node resource api/handlers/otaFetchReservationRequestHandler.js
Uploading node resource api/handlers/otaHandlers.js
Uploading node resource api/handlers/otaReservationHandler.js
Uploading node resource api/handlers/owsFetchReservationRequestHandler.js
Uploading node resource api/handlers/unacceptableRequestHandler.js
Uploading node resource api/helpers/cheerio.js
Uploading node resource api/helpers/config.js
Uploading node resource api/helpers/context.js
Uploading node resource api/helpers/librato.js
Uploading node resource api/helpers/logger.js
Uploading node resource api/helpers/loggly.js
Uploading node resource api/helpers/ows.js
Uploading node resource api/helpers/owsParams.js
Uploading node resource api/helpers/owsRequest.js
Uploading node resource api/helpers/resourceRequest.js
Uploading node resource api/helpers/template.js
Uploading node resource api/parsers/availabilityResponseParser.js
Uploading node resource api/parsers/cancellationResponseParser.js
Uploading node resource api/parsers/fetchReservationResponseParser.js
Uploading node resource api/parsers/fetchRoomResponseParser.js
Uploading node resource api/parsers/headerResponseParser.js
Uploading node resource api/parsers/otaAvailabilityRequestParser.js
Uploading node resource api/parsers/otaCancellationRequestParser.js
Uploading node resource api/parsers/otaFetchReservationRequestParser.js
Uploading node resource api/parsers/otaReservationRequestParser.js
Uploading node resource api/parsers/reservationResponseParser.js
Uploading node resource api/templates/availability.request.ows.xml
Uploading node resource api/templates/availability.response.ota.xml
Uploading node resource api/templates/cancellation.request.ows.xml
Uploading node resource api/templates/cancellation.response.ota.xml
Uploading node resource api/templates/fetch.reservation.request.ows.xml
Uploading node resource api/templates/fetch.reservation.response.ota.xml
Uploading node resource api/templates/fetchRoom.request.ows.xml
Uploading node resource api/templates/reservation.request.ows.xml
Uploading node resource api/templates/reservation.response.ota.xml
Uploading node resource api/validators/countryValidator.js
Uploading node resource api/validators/otaFetchReservationValidator.js
Uploading node resource app.js
Uploading node resource config/non-prod.json
Uploading node resource config/prod.json
Uploading node resource node_modules_apickli.zip
Uploading node resource node_modules_async.zip
Uploading node resource node_modules_builder-builder.zip
Uploading node resource node_modules_body-parser.zip
Uploading node resource node_modules_csvtojson.zip
Uploading node resource node_modules_del.zip
Uploading node resource node_modules_cheerio.zip
Uploading node resource node_modules_express.zip
Uploading node resource node_modules_i18n-iso-countries.zip
Uploading node resource node_modules_handlebars.zip
Uploading node resource node_modules_express-winston.zip
Uploading node resource node_modules_jstoxml.zip
Uploading node resource node_modules_librato-node.zip
Uploading node resource node_modules_mkdirp.zip
Uploading node resource node_modules_moment-range.zip
Uploading node resource node_modules_moment.zip
Uploading node resource node_modules_pretty-data.zip
Uploading node resource node_modules_nconf.zip
Uploading node resource node_modules_require-dir.zip
Uploading node resource node_modules_loggly.zip
Uploading node resource node_modules_shortid.zip
Uploading node resource node_modules_sinon.zip
Uploading node resource node_modules_underscore.zip
Uploading node resource node_modules_underscore.string.zip
Uploading node resource node_modules_winston.zip
Uploading node resource package.json
Uploading node resource node_modules_request.zip
Uploading node resource node_modules_winston-loggly.zip
Uploading policy AssignMessage.404.xml
Uploading policy AssignMessage.InvalidApiKeyForGivenResource.xml
Uploading policy AssignMessage.PutVariableValuesToResponseHeaders.xml
Uploading policy AssignMessage.ReturnStatusResponse.xml
Uploading policy AssignMessage.Set500ErrorVariables.xml
Uploading policy AssignMessage.SetApiKeyNotSuppliedErrorVariables.xml
Uploading policy AssignMessage.SetApigeeAuthenticationErrorVariables.xml
Uploading policy AssignMessage.SetDefaultContentType.xml
Uploading policy AssignMessage.SetIPAccessErrorVariables.xml
Uploading policy AssignMessage.SetInvalidApiKeyErrorVariables.xml
Uploading policy AssignMessage.SetQuotaErrorVariables.xml
Uploading policy AssignMessage.SetQuotaInfo.xml
Uploading policy AssignMessage.SetRequestorIdErrorVariables.xml
Uploading policy AssignMessage.SetSpikeErrorVariables.xml
Uploading policy AssignMessage.SetXmlValidationErrorVariables.xml
Uploading policy ExtractVariables.GetAvailabilityRequestVariables.xml
Uploading policy ExtractVariables.GetAvailabilityResponseVariables.xml
Uploading policy ExtractVariables.GetCancellationRequestVariables.xml
Uploading policy ExtractVariables.GetCancellationResponseVariables.xml
Uploading policy ExtractVariables.GetRequestMessageType.xml
Uploading policy ExtractVariables.GetReservationRequestVariables.xml
Uploading policy ExtractVariables.GetReservationResponseVariables.xml
Uploading policy InvalidateCache.AvailabilityResponse.xml
Uploading policy JavaScript.AuthorizeIpAddress.xml
Uploading policy JavaScript.ConvertConfigurationToJson.xml
Uploading policy JavaScript.ExtractConfigurationVariables.xml
Uploading policy JavaScript.ExtractInvalidateCacheRequestVariables.xml
Uploading policy JavaScript.ModifyAvailabilityCacheResponse.xml
Uploading policy JavaScript.SendToLoggly.xml
Uploading policy KeyValueMap.GetApiConfiguration.xml
Uploading policy LookupCache.GetApiConfiguration.xml
Uploading policy MessageValidation.Xml.xml
Uploading policy PopulateCache.ApiConfiguration.xml
Uploading policy Quota.HourlyApp.xml
Uploading policy RaiseFault.GoToFaultRules.xml
Uploading policy RaiseFault.Xml.xml
Uploading policy ResetQuota.HourlyApp.xml
Uploading policy ResponseCache.AvailabilityResponse.xml
Uploading policy ServiceCallout.AuthenticateToApigee.xml
Uploading policy SpikeArrest.Global.xml
Uploading policy StatisticsCollector.SetCustomData.xml
Uploading policy VerifyApiKey.ValidateAppId.xml
Uploading target default
Deploying revision 205 of b2b-otaxml to intg
Going to POST to https://api.enterprise.apigee.com/v1/o/org-here/e/intg/apis/b2b-otaxml/revisions/205/deployments
Going go send command action=deploy&override=true&delay=60
Deployment on intg result: "{\n  \"code\" : \"distribution.NoProxiesToDeploy\",\n  \"message\" : \"No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy\",\n  \"contexts\" : [ ]\n}"
Error: No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy
Error: No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy
at Request._callback (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:652:12)
at Request.self.callback (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:198:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:1082:10)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:1009:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)
Warning: Command failed: Deployment on intg result: "{\n  \"code\" : \"distribution.NoProxiesToDeploy\",\n  \"message\" : \"No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy\",\n  \"contexts\" : [ ]\n}"
Error: No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy
Error: No proxies available in apiproxy b2b-otaxml and revision 205. At least one proxy required to deploy
at Request._callback (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:652:12)
at Request.self.callback (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:198:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:1082:10)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/request/request.js:1009:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)
 Use --force to continue.
```

Have a look between these two lines - no proxy files:
```
Uploading target default
Deploying revision 205 of b2b-otaxml to intg
```

When I force our CI tool to revert to 0.5.4 of apigeetool, the whole build works fine (I haven't tried the versions in between):
```
Uploading target default
Uploading proxy admin
Uploading proxy default
Uploading proxy monitoring
Deploying revision 206 of b2b-otaxml to intg
```

Haven't had time to check the code myself yet.

**Comment by theganyo** [comment]
I'm sorry for the inconvenience. I'm looking into it now.

**Comment by theganyo** [comment]
Fixed in 0.6.2. Please let me know if you have any further issues. Thanks for your patience!

**Comment by oseymen-apigee** [comment]
Thanks a lot @theganyo - this time I am getting this with 0.6.2:

```
...
Uploading policy ServiceCallout.AuthenticateToApigee.xml
Uploading policy SpikeArrest.Global.xml
Uploading policy StatisticsCollector.SetCustomData.xml
Uploading policy VerifyApiKey.ValidateAppId.xml
Uploading target default

TypeError: Object #<Object> has no method 'parse'
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:513:28
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:187:20
at replenish (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:322:21)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:333:15
at Object.async.forEachLimit.async.eachLimit (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:226:35)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:511:11
at findProxies (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:503:3)
at uploadProxies (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:508:3)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:104:7
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:689:13
Warning: Command failed: 
TypeError: Object #<Object> has no method 'parse'
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:513:28
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:187:20
at replenish (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:322:21)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:333:15
at Object.async.forEachLimit.async.eachLimit (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:226:35)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:511:11
at findProxies (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:503:3)
at uploadProxies (/home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:508:3)
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/lib/commands/deployproxy.js:104:7
at /home/rof/.nvm/v0.10.36/lib/node_modules/apigeetool/node_modules/async/lib/async.js:689:13
 Use --force to continue.
```

**Comment by theganyo** [comment]
Oh wow. That's an old version of Node... apparently the parse function was added after that. Ok. I'll have to use a different set of functions.

**Comment by oseymen-apigee** [comment]
No @theganyo - please don't modify your code to support node 0.10.0. We can look at changing that. We were forcing that version as that is the version supported by Apigee.

Thanks a lot for all your help.

**Comment by theganyo** [comment]
It's ok. It was an easy fix. It's in now. :)

**Comment by oseymen-apigee** [comment]
thanks a lot @theganyo - it is working perfectly on node 0.10.0.
