### ISSUE TITLE
API errors not reported?

### ISSUE THREAD

**Issue by shaqq** [apigee/apigeetool-node#39]
@theganyo or who else this concerns

It looks like the `-V` or `--debug -D` flags don't return errors from the API itself. Here's what I'm getting back:

```sh
Please report a bug if this causes problems.
Error: Error: Error uploading policy: 400
Error: Error uploading policy: 400
    at Request._callback (/usr/local/lib/node_modules/apigeetool/lib/commands/deployproxy.js:376:18)
    at Request.self.callback (/usr/local/lib/node_modules/apigeetool/node_modules/request/request.js:123:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/apigeetool/node_modules/request/request.js:1047:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/apigeetool/node_modules/request/request.js:998:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

Is there an option I'm missing here? At first glance, the error messages don't seem to be printed out the console:

https://github.com/apigee/apigeetool-node/blob/2198cff354e7d220dc839aff24db4b0205e28597/lib/commands/deployproxy.js#L369-L377

Though I haven't done a deep-dive into the code yet. Let me know how I can help. Thanks!

**Comment by Mattzr** [comment]
Hi,
Facing the same issue when trying to deploy an api proxy which has a Service Callout Policy. The error is not reported in the console and have to fiddle it to see what's wrong. Getting a 500 and not 400 though

Any update on this one ? 

@theganyo

**Comment by surabhi-gupta-jll** [comment]
I am getting the same error. does any one have solution?

**Comment by khparhami** [comment]
Same error when trying to upload a Service Callout Policy in a shared flow. Only happens when deploying using API, UI works fine!
